"""create workout_logs table

Revision ID: 21bdbc24b5cf
Revises: fb54860fd89d
Create Date: 2026-06-14 13:54:13.468778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bdbc24b5cf'
down_revision: Union[str, Sequence[str], None] = 'fb54860fd89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_logs_user_logged_at', 'workout_logs', ['user_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.drop_index('idx_workout_logs_user_logged_at', table_name='workout_logs')
    op.drop_table('workout_logs')
    # ### end Alembic commands ###
