"""create daily_check_ins table

Revision ID: 90760bd9d595
Revises: 21bdbc24b5cf
Create Date: 2026-06-14 14:32:19.607949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90760bd9d595'
down_revision: Union[str, Sequence[str], None] = '21bdbc24b5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calorie_target', sa.Float(), nullable=True),
    sa.Column('calorie_actual', sa.Float(), nullable=True),
    sa.Column('protein_target', sa.Float(), nullable=True),
    sa.Column('protein_actual', sa.Float(), nullable=True),
    sa.Column('workout_target_minutes', sa.Integer(), nullable=True),
    sa.Column('workout_actual_minutes', sa.Integer(), nullable=True),
    sa.Column('adherence_status', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_checkin_user_date', 'daily_check_ins', ['user_id', 'date'], unique=True)
    op.create_index(op.f('ix_daily_check_ins_id'), 'daily_check_ins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_check_ins_id'), table_name='daily_check_ins')
    op.drop_index('idx_daily_checkin_user_date', table_name='daily_check_ins')
    op.drop_table('daily_check_ins')
    # ### end Alembic commands ###
